import { watch } from 'node:fs'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const currentDirectory = fileURLToPath(new URL('.', import.meta.url))
const sourceDirectory = path.resolve(currentDirectory, '../src')

const preamble = [
  '// This file is autogenerated. Do not edit it directly.',
  '// To update it, modify the corresponding source file and run `pnpm inline-scripts`.',
].join('\n')

async function findTemplateFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true })
  const files = await Promise.all(
    entries.map(async (entry) => {
      const entryPath = path.join(directory, entry.name)

      if (entry.isDirectory()) {
        return findTemplateFiles(entryPath)
      }

      return entry.name.endsWith('.template.js') ? [entryPath] : []
    }),
  )

  return files.flat()
}

function minifyTemplate(sourceContent) {
  return sourceContent.trim()
}

async function buildFile(sourceFile) {
  const sourceContent = await readFile(sourceFile, 'utf8')
  const escapedCode = JSON.stringify(minifyTemplate(sourceContent))
  const output = [
    preamble,
    '',
    '// prettier-ignore',
    `export const script = ${escapedCode};`,
    '',
  ].join('\n')
  const outputFilename = sourceFile.replace('.template.js', '.min.ts')
  await writeFile(outputFilename, output)
}

async function run() {
  const files = await findTemplateFiles(sourceDirectory)
  await Promise.all(files.map(buildFile))
  return files
}

const files = await run()

if (process.argv.includes('--watch') || process.argv.includes('-w')) {
  console.log('Processing *.template.js files in watch mode...')

  files.forEach((file) => {
    watch(file, (eventType) => {
      if (eventType === 'change') {
        buildFile(file)
      }
    })
  })
}
