export const name = 'base-ui-vue'
export const version = '0.0.0'

export * from './accordion'
export * from './avatar'
export * from './button'
export * from './collapsible'
export * from './fieldset'
export * from './merge-props'
export * from './use-render'
export { Slot } from './utils/slot'
